### ISSUE TITLE
wcb rebuilds too much.

### ISSUE THREAD

**Issue by brettviren** [WireCell/waf-tools#8]
Something is invalidating intermediate build products.  This makes any little change require rebuilding **everything**!  Very painful.

```
$ ./wcb
[  5/489] Compiling util/src/WireSchema.cxx
[  6/489] Compiling util/src/WireCellUtil.cxx
... wait until WireSchema.cxx compilation ends
Ctrl-C

$ ls -l build/util/src/WireSchema.cxx*
-rw-rw-r-- 1 bv bv 5071008 Mar 26 16:10 build/util/src/WireSchema.cxx.2.o

$ ./wcb
[  5/489] Compiling util/src/WireSchema.cxx
[  6/489] Compiling util/src/WireCellUtil.cxx
... wait until WireSchema.cxx compilation ends
Ctrl-C

$ ls -l build/util/src/WireSchema.cxx*
-rw-rw-r-- 1 bv bv 5071008 Mar 26 16:11 build/util/src/WireSchema.cxx.2.o
```

**Comment by brettviren** [comment]
It is related to running `./wcb` using Python 3! 

Either in a virtual environment created like:

```
$ python3 -m venv venv
$ source venv/bin/activiate
```

Or simply in the usual Ubuntu 18.04 environment and running like:

```
$ python3 ./wcb
[  5/489] Compiling util/src/WireSchema.cxx
[  6/489] Compiling util/src/WireCellUtil.cxx
... 
[ 40/489] Compiling iface/src/SimpleFrame.cxx
...ctrl-c

$ python3 ./wcb
[  5/489] Compiling util/src/WireSchema.cxx
[  6/489] Compiling util/src/WireCellUtil.cxx
... ctrl-c

$ python2 ./wcb
...
[  5/489] Compiling util/src/WireSchema.cxx
[  6/489] Compiling util/src/WireCellUtil.cxx
...
[ 36/489] Compiling iface/src/FrameTools.cxx
... ctrl-c

$ python2 ./wcb
[ 20/489] Compiling util/src/PluginManager.cxx
[ 22/489] Compiling util/src/Persist.cxx
...
```

**Comment by HaiwangYu** [comment]
Seems this is not in wire-cell/master yet. Could you update the wire-cell/master with this? We are having more users recently. This fix could be a big help. Thanks!

**Comment by brettviren** [comment]
Thanks, just pushed WireCell/wire-cell-toolkit@69474ed89b09708619850be62978452e75b2fa70

**Comment by HaiwangYu** [comment]
Seems latest larsoft versions are getting rid of python2 by default. Like in `larsoft v08_47_00`, seems python 2 is just not available:

```bash
$./wcb
Traceback (most recent call last):
  File "/cvmfs/larsoft.opensciencegrid.org/products/postgresql/v9_6_11b/Linux64bit+3.10-2.17-p372/lib/python3.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/cvmfs/larsoft.opensciencegrid.org/products/postgresql/v9_6_11b/Linux64bit+3.10-2.17-p372/lib/python3.7/site-packages/site.py", line 3, in __boot
    import os
ImportError: No module named os
```

`python ./wcb` works fine, but still invalidating intermediate build products and re-compiles.

**Comment by brettviren** [comment]
Darn.  

Okay, it was a hacky "fix".  I'll reopen and put wcb back to not specifying the version.

**Comment by wenqiang-gu** [comment]
Hi Haiwang,

 

I think larsoft still supports python2 but with a different subversion. For example,

 

"larsoft" "v08_48_00" "Linux64bit+3.10-2.17" "e19:prof:py2" ""

 

Best,

Wenqiang

**Comment by HaiwangYu** [comment]
Good point @wenqiang-gu . So for development that needs rebuilding wire-cell repeatedly, we may want to use those py2 larsoft versions.

**Comment by brettviren** [comment]
Hi @HaiwangYu and @wenqiang-gu 

This should be fixed now.

The problem is that Python3's `set` object does not produce a stable order.  Both 2 and 3 `set` is not specially ordered but with Python2, each run of some code making a `set` always gets the same order.  With 3 each time the same code is run the order may be different.  Probably Python3 uses the underlying pointer value in the hash but I've not yet found the documentation for this.

This unstable order mean that `waf` thought each new run the dependencies changed when actually just their apparent order did.

The last fix converts the `set` into a `list` and does an explicit `.sort()` so stability should be assured in both 2 and 3 now.

**Comment by HaiwangYu** [comment]
Hi @brettviren ,
This is really great! I tested it with python3 and it works as expected. Thanks!
